### PR TITLE
Added content to README.md

### PR DESCRIPTION
**Pull request by jlam55555**

### CODE REVIEW

**Comment by Huntrr** [comment]
proper markdown would have a full space between paragraphs, so there should be a space between line 1 and 2 here. otherwise lgtm

**Comment by Huntrr** [comment]
i dont know why, but for some reason i'm subscribed to this repo, so i felt the need to review a pull request

**Comment by junewunder** [comment]
I'm thinking I should make "alumni" a github group, that way you're not autosubbed to stuff

**Comment by junewunder** [comment]
But thanks for reviewing the PR hahah

**Pull request merged**
