### PR TITLE
Redirect div

### PR DESCRIPTION
**Pull request by jlam55555**
Made `<div>` popup (not the action button in the top right) happen before DOM loading (before `$(window).load()` &mdash; it hasn't given me problems, but please confirm?) and re-styled it.

### CODE REVIEW

**Comment by junewunder** [comment]
certainly smoother. I think that the popup shouldn't actually cover the whole page though. If it was in the top right then that'd be great.  I'm just thinking that people should be able to immediately use their email, google, etc.  And with the full screen popup they have to wait to click "back to work"

**Comment by junewunder** [comment]
buuut I do like the style changes you made! good job!

**Comment by jlam55555** [comment]
Ok, will do. I'll move it out of the way

**Comment by jlam55555** [comment]
I changed it up a bit&mdash; now it floats up at top, covering only a small portion of the page.

Ideally, it would even be able to _push down_ the page contents, but I'm not sure how I could do this in a way that would affect all webpages equally.

**Comment by junewunder** [comment]
oooo I like that idea with pushing everything down, should I merge now and we figure that out later? or is it probably relatively easy?

**Comment by jlam55555** [comment]
Not too easy because of the variability of different websites' structures. I don't know how to do it, but I believe I've seen projects on GitHub before that do this. I'll check them out

For now, you can merge

**Comment by junewunder** [comment]
This is a midnight idea so it probably won't work...

What if we give the HTML element a top padding of X pixels and give the top element an absolute position of -X. I'm not sure if you can do that though. Just writing it down so I don't forget by morning

**Comment by jlam55555** [comment]
I tried that already&mdash; the problem is, the websites' scripts may dynamically position their elements, overriding your styles. So therefore, what I tried was making the entire `<body>` element an absolutely positioned element and moving it down (because it is not usually positioned), but that didn't work for some websites (e.g. GitHub and Google)

**Comment by Huntrr** [comment]
then do it dynamically yourself? `$("body, html").css('margin-top', '20px');` seems to work.

won't work on pages with any elements that are `position: fixed;` of course, but that's probably not a big deal.

**Comment by junewunder** [comment]
I wouldn't think we want to change the `body` element because `header` and `footer` elements can go outside of the body. Right?

**Comment by Huntrr** [comment]
idk if some websites are designed like that, but they definitely shouldn't be. `<body>` should contain all visible page content.

http://stackoverflow.com/questions/5492492/in-html5-can-the-header-and-footer-tags-appear-outside-of-the-body-tag

**Comment by junewunder** [comment]
TIL! Thank you, that indeed is how websites work haha. Okay so like I guess that would work then.

**Pull request merged**
